AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation basics - S3 bucket'

Parameters:
  BucketName:
    Type: String
    Description: 'S3 bucket name (must be globally unique)'

Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

Outputs:
  BucketName:
    Description: 'S3 bucket name'
    Value: !Ref MyBucket
  BucketArn:
    Description: 'S3 bucket ARN'
    Value: !GetAtt MyBucket.Arn
